name: musicplayer
description: "A new Flutter project."
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  audioplayers: ^6.4.0
  file_picker: ^9.1.0
  flutter:
    sdk: flutter
  flutter_media_metadata: ^1.0.0+1
  flutter_staggered_animations: ^1.1.1
  just_audio: ^0.9.46
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  sliding_up_panel: ^2.0.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0




flutter:
  uses-material-design: true
  assets:
    - assets/images/default_cover.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
