name: musicplayer
description: "A new Flutter project."
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  audioplayers: ^6.4.0
  audiotags: ^1.4.3
  file_picker: ^9.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_media_metadata: ^1.0.0+1
  hero_animation: ^1.1.4
  just_audio: ^0.9.46
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  sliding_up_panel: ^2.0.0+1
  audio_service: ^0.18.12



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/playstore-icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/playstore-icon.png"


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
